Humble対応
rt-net/raspimouse_ros2_examples pull request #41
Opened 2023-01-19 10:01 UTC by shu-rt

# What does this implement/fix?

Humbleに対応します

# Does this close any currently open issues?

No

# How has this been tested?

実機で動作確認済み。  
ただし、LDSドライバーの動作に不具合があり、SLAM部分の動作確認はできていません。

# Any other comments?

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-07-10 06:36 UTC, YusukeKato commented
実機の Raspberry Pi Mouse ですべてのサンプルの動作確認ができました。

2023-07-10 06:37 UTC, YusukeKato commented
SLAM実行時に以下のエラーが発生するため、対応をお願いします。
このエラーはRVizのFrame Rateを下げることで対処できます。
Frame Rateは`raspimouse_ros2_examples/config/default.rviz`を編集することで設定できます。
READMEに「Frame Rateを下げることで以下のエラーに対処できる」という説明を書くとよいかもしれません。
```
[rviz2-2] [ERROR] [1688627677.219277359] [rviz2]: Lookup would require extrapolation into the future.  Requested time 1688627677.380703 but the latest data is at time 1688627677.201177, when looking up transform from frame [laser] to frame [map]
```

2023-07-10 06:39 UTC, YusukeKato commented
SLAM実行後の地図の保存時に以下のエラーが発生するため、対応をお願いします。
```
[ERROR] [1688704248.384633458] [map_saver_cli]: Unexpected problem appear: parameter 'save_map_timeout' has invalid type: Wrong parameter type, parameter {save_map_timeout} is of type {double}, setting it to {integer} is not allowed.
```
このエラーは以下のようにコマンドを修正するとよいと思います。
```
# 修正前
ros2 run nav2_map_server map_saver_cli -f ~/testmap --ros-args -p save_map_timeout:=10000
# 修正後
ros2 run nav2_map_server map_saver_cli -f ~/testmap --ros-args -p save_map_timeout:=10000.0
```

2023-07-10 06:52 UTC, YusukeKato commented
IMUセンサを使用する時、ケーブルを何度か抜き差ししないと接続がうまくいきませんでした。
あまり重要ではないですが、READMEに注意書きをしておくと良いかもしれません。

2023-07-10 06:59 UTC, YusukeKato commented
rosdepコマンド実行時、以下のエラーが発生しました。
このエラーは先に`rt_usb_9axisimu_driver`パッケージをインストールしておくことで解決しました。
対応をお願いします。
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
raspimouse_ros2_examples: Cannot locate rosdep definition for [rt_usb_9axisimu_driver]
```

2023-07-10 07:03 UTC, YusukeKato approved these changes
とても良いと思います！

2023-07-21 05:44 UTC, ShotaAk requested changes
いくつかコメントしました。確認お願いします

2023-07-21 05:44 UTC, ShotaAk commented on README.en.md
> +    - [Humble Hawksbill](https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html)
humbleのみを記載してください。
対応しているOSもUbuntu 22.04に変更お願いします。

foxyについては、X7のREADMEのようにfoxy-develブランチを案内してください。
https://github.com/rt-net/crane_x7_ros/tree/ros2#supported-ros-2-distributions

2023-07-21 05:44 UTC, ShotaAk commented on README.md
> +    - [Humble Hawksbill](https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html)
別のコメントと同様に、humbleのみを記載してください。

2023-07-21 05:44 UTC, ShotaAk commented on README.en.md
> +$ git clone -b $ROS_DISTRO-devel https://github.com/rt-net/rt_usb_9axisimu_driver.git
rt_usb_9axisimu_driverはrosdepでインストールされるはずです。
再度確認お願いします

```suggestion
```

2023-07-21 05:44 UTC, ShotaAk commented on README.md
> +$ git clone -b $ROS_DISTRO-devel https://github.com/rt-net/rt_usb_9axisimu_driver.git
他のコメント同様に、rt_usb_9axisimu_driverのrosdep インストールが確認できたら削除お願いします。
```suggestion
```

2023-07-24 04:50 UTC, shu-rt commented on README.en.md
> +$ git clone -b $ROS_DISTRO-devel https://github.com/rt-net/rt_usb_9axisimu_driver.git
手元で確認できました！提案取り込みます。  
```bash
executing command [sudo -H apt-get install -y ros-humble-rt-usb-9axisimu-driver]
```

2023-07-24 05:00 UTC, shu-rt commented on README.en.md
> +    - [Humble Hawksbill](https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html)
こちらのコミットまでで対応しました  
https://github.com/rt-net/raspimouse_ros2_examples/pull/41/commits/c471d0bc67f2216f710b178521bc22d4adbb27b0

2023-07-24 05:00 UTC, shu-rt commented on README.md
> +    - [Humble Hawksbill](https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html)
上記と合わせて対応しました。

2023-07-24 05:25 UTC, ShotaAk reviewed
1点気になったのでコメントしました

2023-07-24 05:25 UTC, ShotaAk commented on README.en.md
> +- Humble (This repository)
branchのほうが正しいかも？

```suggestion
- Humble (This branch)
```

2023-07-24 05:25 UTC, ShotaAk commented on README.md
> +- Humble (This repository)
```suggestion
- Humble (This branch)
```

2023-07-24 05:26 UTC, shu-rt commented on README.en.md
> +- Humble (This repository)
あ、そうですね！変更取り込みますー

2023-07-24 05:28 UTC, ShotaAk approved these changes
LGTM

2023-07-24 05:51 UTC, merged