RGBカメラによるライントレースの実装
rt-net/raspimouse_ros2_examples pull request #47
Opened 2023-11-22 07:45 UTC by YusukeKato

# What does this implement/fix?

ラズパイマウスに搭載したRGBカメラを使用してライントレースを行うサンプルを実装しました。

# Does this close any currently open issues?

しません。

# How has this been tested?

## シミュレータ環境で動作確認
端末1で下記のコマンドを実行して、シミュレータを起動
```sh
ros2 launch raspimouse_gazebo raspimouse_with_line_follower_field.launch.py use_rgb_camera:=true camera_downward:=true
```

端末2で下記のコマンドを実行して、RGBカメラによるライントレースのノードを起動
```sh
ros2 launch raspimouse_ros2_examples camera_line_follower.launch.py mouse:=false use_camera_node:=false
```

端末3で下記のコマンドを実行して、switchesトピックを介してcmd_velトピックの配信をON/OFF
```sh
ros2 topic pub --once /switches raspimouse_msgs/msg/Switches "{switch0: true, switch1: false, switch2: false}"
```

# Any other comments?

シミュレータで動作確認する場合、下記のリポジトリが必要です。

raspimouse_descriptionのros2ブランチ

https://github.com/rt-net/raspimouse_description/tree/ros2

raspimouse_simのros2ブランチ

https://github.com/rt-net/raspimouse_sim/tree/ros2

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-11-28 01:52 UTC, ShotaAk commented
![image](https://github.com/rt-net/raspimouse_ros2_examples/assets/18494952/385a6f91-3c7f-4f18-9ca9-66316dcfc69d)

オドメトリがずれますね。raspimouse_simで呼び出しているコントローラのパラメータを見直して、改善するか確認してほしいです。

（自己位置補正がないので限界はあります）

2023-11-28 02:48 UTC, ShotaAk requested changes
動作確認できました。コードレビューは途中です。

一旦コメントの確認と修正お願いします。

2023-11-28 02:48 UTC, ShotaAk commented on include/raspimouse_ros2_examples/camera_line_follower_component.hpp
> +// Copyright 2020 RT Corporation
```suggestion
// Copyright 2023 RT Corporation
```

2023-11-28 02:48 UTC, ShotaAk commented on launch/camera_line_follower.launch.py
> +# Copyright 2020 RT Corporation
```suggestion
# Copyright 2023 RT Corporation
```

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +// Copyright 2020 RT Corporation
```suggestion
// Copyright 2023 RT Corporation
```

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;
他コードへの影響を抑えるため、usingはnamespace内で使用してください。

```cpp
namespace hoge
{
  using fuga = piyo;
}
```

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  auto msg = std::make_unique<sensor_msgs::msg::Image>();
msgは使われてないです。
```suggestion
```

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  auto cv_img = cv_bridge::toCvShare(msg_image, msg_image->encoding);
エラーが出なければconst を付けてほしいです。

`const auto hoge;`

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  result_msg->is_bigendian = false;
is_bigendian = false;の処理がなぜ必要なのか、コメントで補足してほしいです。

2023-11-28 02:48 UTC, ShotaAk commented on include/raspimouse_ros2_examples/camera_line_follower_component.hpp
> +  std::string mat_type2encoding(int mat_type);
内部変数を変えない場合はconstを付けてください。
また、引数にもconstを付けてください。
```suggestion
  std::string mat_type2encoding(const int mat_type) const;
```

2023-11-28 02:48 UTC, ShotaAk commented on include/raspimouse_ros2_examples/camera_line_follower_component.hpp
> +// Copyright 2020 RT Corporation
ソースファイルも同様に対応してください。

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
cmd_vel_　は他の関数から参照されていないため、メンバ変数にする必要がないです。
関数内で宣言してください

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  switches_ = raspimouse_msgs::msg::Switches();  // Reset switch values
メンバ変数switches_を書き換える箇所が複数存在しているため、改善したいです。

おそらく、シミュレーション時にswitchesトピックが定期配信されていないことへの対策だと思われます。

switchesトピックを定期配信するノードを、raspimouse_fakeに追加しましょう

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  switches_ = raspimouse_msgs::msg::Switches();  // Reset switch values
使用イメージ
```bash
# switchesトピックは定期配信されている

# switch1のステータスをtrueにする
$ ros2 service call std_srvs/SetBool set_switch1 "data: True"
```

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  const double OBJECT_AREA_THRESHOLD = 0.01;  // 0.0 ~ 1.0
コンパイル時に定数化できるのでconstexprを使いましょう。

```suggestion
  constexpr double LINEAR_VEL = 0.2;  // unit: m/s
  constexpr double ANGULAR_VEL = -0.8;  // unit: rad/s
  constexpr double TARGET_AREA = 0.1;  // 0.0 ~ 1.0
  constexpr double OBJECT_AREA_THRESHOLD = 0.01;  // 0.0 ~ 1.0
```

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  // Detects an object and tracks it
ここではオブジェクトをdetectしてないので文章を変えてください。

detectされたobjectを追うように速度を出す　ならわかります。

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  }
ここの処理はswitchesのcallback関数に移動したほうが分かりやすいです。

そうするとswitches_変数が不要になります。

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  if (!can_publish_cmdvel_) {
can_publish_cmdvel_がfalseでもcmd_velをpublishしているので、変数名と処理が一致してません。

enable_following_ のような変数名はどうでしょうか？

2023-11-28 02:48 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +void Camera_Follower::following(const cv::Mat & input_frame, cv::Mat & result_frame)
ここでは追跡ではなく、追跡するための物体検出をしています。
関数名を変更してください。

2023-11-28 09:05 UTC, ShotaAk requested changes
その他のコードを読みました。コメントの確認おねがします。

2023-11-28 09:05 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +      cv::FONT_HERSHEY_SIMPLEX, 1, cv::Scalar(255, 0, 0), 2);
テキストが見にくいので明るい色に変えてください。

![image](https://github.com/rt-net/raspimouse_ros2_examples/assets/18494952/4221654a-480a-42e6-bc93-c82e7b63d04b)

2023-11-28 09:05 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +    object_is_detected_ = true;
object_is_detected_  の変更箇所をわかりやすくするため、
この関数の返り値をbool型に変更してください

例（image_callback()内での処理）：
```cpp
 // following関数名は適宜変更してください。
 object_is_detected_ = following();
```

2023-11-28 09:05 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +    object_is_detected_ = true;
この変更に伴い、following関数をconstメンバ関数にしてください。

```cpp
bool following() const;
```

2023-11-28 09:05 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  auto request = std::make_shared<std_srvs::srv::SetBool::Request>();
サービスが失敗したらFAILUREするように実装してくれると嬉しいです。

2023-12-05 05:59 UTC, YusukeKato commented on src/camera_line_follower_component.cpp
> +  result_msg->is_bigendian = false;
is_bigendianをfalseにしなくても動作確認できたので、この行を削除しました。

2023-12-05 06:42 UTC, YusukeKato commented on src/camera_line_follower_component.cpp
> +  if (!can_publish_cmdvel_) {
ありがとうございます。
enable_following_に変更しました。

2023-12-05 06:49 UTC, YusukeKato commented on src/camera_line_follower_component.cpp
> +void Camera_Follower::following(const cv::Mat & input_frame, cv::Mat & result_frame)
detecting_ling()に変更しました。

2023-12-05 06:51 UTC, YusukeKato commented on src/camera_line_follower_component.cpp
> +      cv::FONT_HERSHEY_SIMPLEX, 1, cv::Scalar(255, 0, 0), 2);
青から白に変更しました。

2023-12-05 07:13 UTC, YusukeKato commented on src/camera_line_follower_component.cpp
> +    object_is_detected_ = true;
この関数にconstを付けると
```cpp
object_normalized_area_ = max_area / (input_frame.rows * input_frame.cols);
```
の行でエラーが発生します。

2023-12-05 07:17 UTC, YusukeKato commented on src/camera_line_follower_component.cpp
> +  auto request = std::make_shared<std_srvs::srv::SetBool::Request>();
「サービスが失敗したらFAILUREする」とは具体的にはどういう処理を指すでしょうか。
単純にプログラムを終了すれば良いでしょうか。

2023-12-06 02:41 UTC, ShotaAk commented
オドメトリの調整いい感じです
![image](https://github.com/rt-net/raspimouse_ros2_examples/assets/18494952/b45bdee6-459b-48ab-9346-b15afa693ba2)

2023-12-06 02:56 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
>    // when the number of pixels of the object is greater than the threshold.
ここではDetectしてないので訂正してほしいです。（画像処理もここで行われている　と勘違いします）

```suggestion
  // Follow the line
  // when the number of pixels of the object is greater than the threshold.
```

2023-12-06 02:56 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +    object_is_detected_ = true;
変数が２つありましたね、変更なしでOKです。

2023-12-06 05:08 UTC, ShotaAk requested changes
細かいところにコメントしました。確認お願いします

2023-12-06 05:08 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  auto request = std::make_shared<std_srvs::srv::SetBool::Request>();
motor_power サービスが失敗する可能性もあるので、そのときはon_activateが失敗するように実装お願いします。

参考情報：https://robotics.stackexchange.com/a/96076/37280

```cpp
auto future_result = motor_power_client_->async_send_request(request);
if (rclcpp::spin_until_future_complete(this->get_node_base_interface(), result) 
    != rclcpp::executor::FutureReturnCode::SUCCESS)
{
  return CallbackReturn::FAILURE;
}
```

ただ、spin周りはROS 2仕様による不具合があるので、エラーが出る場合はあきらめましょう。
https://github.com/ros2/rclcpp/issues/1916

2023-12-06 05:08 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +{
これもconstメンバ関数にできそうです

2023-12-06 09:13 UTC, YusukeKato commented
下記のコードを追加したところエラーが発生し、ライントレースは正常に動きませんでした。
```cpp
auto future_result = motor_power_client_->async_send_request(request);
if (rclcpp::spin_until_future_complete(this->get_node_base_interface(), future_result) 
    != rclcpp::FutureReturnCode::SUCCESS)
{
  return CallbackReturn::FAILURE;
}
```

エラー内容↓
```
[component_container_mt-1] [ERROR] [1701853265.381801467] [camera_follower]: Caught exception in callback for transition 13
[component_container_mt-1] [ERROR] [1701853265.381822847] [camera_follower]: Original error: Node '/camera_follower' has already been added to an executor.
[component_container_mt-1] [WARN] [1701853265.381833738] [camera_follower]: Error occurred while doing error handling.
[lifecycle_node_manager-2] [ERROR] [1701853265.382155052] [manager]: Failed to activate nodes.
[component_container_mt-1] [WARN] [1701853265.452359650] [LifecyclePublisher]: Trying to publish message on the topic '/result_image', but the publisher is not activated
```

2023-12-06 09:26 UTC, ShotaAk commented
エラーについて了解です。ノード外部にexecutorがいるのでspinの権限を取られているんですよね。。。

ひとまずこのままにしましょう

2023-12-06 09:36 UTC, merged