READMEにカメラライントレースの情報を追記
rt-net/raspimouse_ros2_examples pull request #49
Opened 2024-01-19 08:28 UTC by YusukeKato

# What does this implement/fix?

READMEにRGBカメラによるライントレースの情報を追加します。

# Does this close any currently open issues?

しません。

# How has this been tested?

ドキュメントの変更のみなのでテストは行っていません。

# Any other comments?

ありません。

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-01-25 01:45 UTC, ShotaAk requested changes
文章について一部コメントしてます。

実装に課題があるので調査してほしいです。

画像処理そのものにどれくらい時間が掛かっているのかも調査お願いします。

2024-01-25 01:45 UTC, ShotaAk commented on README.md
> +
スイッチ操作の説明も追加してください

2024-01-25 01:45 UTC, ShotaAk commented on README.md
> +**画像を表示するとノードの動作が不安定になり、cmd_velや画像トピックが発行されないことがあります。**
この不安定な挙動は私の環境でも再現しました。

原因を特定してからリリースとしたいです。

例えばカメラ画像追跡サンプルでも同じような症状が発生するのか気になります。

2024-01-25 01:45 UTC, ShotaAk commented on README.md
> +```
画像の輝度平均値に合わせてしきい値を変えたり、
ヒストグラム平坦化を使うことで、明るさの変化に強い実装ができそうです。

改善できるか調べてみてほしいです。

2024-01-25 05:38 UTC, YusukeKato commented
camera_line_follower実行時の時間計測

- ライン検出処理：20ms
- 検出結果の画像トピックの配信処理（rqt_image_view実行中）：30ms
  - rqt_image_viewを実行していない時は1ms以内
- object_trackingもほぼ同じ処理時間

合計約50msの処理をカメラ画像トピック（30FPS）のコールバック関数内で行っているために、処理が間に合っていない可能性があります。

2024-01-25 05:43 UTC, YusukeKato commented on README.md
> +**画像を表示するとノードの動作が不安定になり、cmd_velや画像トピックが発行されないことがあります。**
camera_line_follower実行後、rqt_image_viewを起動すると、スイッチトピックが配信されないことを確認しました（object_trackingではこの挙動は確認できませんでした。スイッチトピックのサブスクライバの有無が関係しているかもしれません）。

対処方法：usb_camの配信頻度を30FPSから10FPSに下げる

原因と思われるもの：https://github.com/rt-net/raspimouse_ros2_examples/pull/49#issuecomment-1909390851

2024-01-25 07:51 UTC, YusukeKato commented on README.md
> +```
輝度の平均値をもとにしきい値を決定するにはadaptiveThreshold関数を使うとできそうです。

参考 : http://opencv.jp/opencv-2svn/cpp/miscellaneous_image_transformations.html

```cpp
# 変更前
cv::inRange(gray, 0, 100, extracted_bin);

# 変更後
cv::adaptiveThreshold(gray, extracted_bin, 255, CV_ADAPTIVE_THRESH_GAUSSIAN_C, CV_THRESH_BINARY_INV, 51, 0);
```

結果画像（パラメータ未調整）↓

![adaptiveThreshold_test](https://github.com/rt-net/raspimouse_ros2_examples/assets/12107761/260c4fc3-4985-407a-a51d-3a10f1b1ed57)

2024-01-25 11:08 UTC, ShotaAk commented on README.md
> +```
いい変更ですね！

2024-01-25 11:30 UTC, ShotaAk commented
@YusukeKato 
調査ありがとうございます。まずは画像処理の実装を変えてみましょうか。

どのステップでどれぐらい処理時間が掛かっているか、処理時間を短縮できるか、検証お願いします。

下記が候補です。
恐らく画像サイズを小さくするだけで、効果が出ると思います。

- グレースケール変換と二値化
  - 対策：画像サイズを小さくする
- ノイズ除去
   - 対策：`cv::morphologyEx`のカーネルサイズを小さくする
- 輪郭抽出
   - 対策：`cv::findContours` のオプションをCHAIN_APPROX_SIMPLEにする
- 最大輪郭の抽出
   - 対策：輪郭抽出でCAHIN_APPROX_SIMPLEを適用する

2024-01-25 11:40 UTC, ShotaAk commented
画像のpublish処理については、画像サイズを小さくすれば改善すると思います。

また、image_transportを使うと改善する可能性あります。

https://github.com/ros-perception/image_transport_tutorials/blob/main/src/my_publisher.cpp#L26-L27

2024-01-25 11:41 UTC, ShotaAk commented on README.md
> +**画像を表示するとノードの動作が不安定になり、cmd_velや画像トピックが発行されないことがあります。**
これについてはまず画像処理の高速化を狙いましょう。

また、画像処理が重くなるとスイッチ処理が実行されないので、実装を変えて対策したいですね。
（subscribeの設定かな？）

2024-01-26 05:45 UTC, YusukeKato commented
画像処理にかかった時間の計測結果は以下のようになりました。

合計

-  inRange() 使用時 : 10ms
- adaptiveThreshold()使用時 : 27ms

内訳

- グレースケール変換 : 1ms
- 2値化
  - inRange() : 1ms
  - adaptiveThreshold() : 20ms
- ノイズ除去
  - inRange()使用時 : 4ms
  - adaptiveThreshold() 使用時 : 2ms
- 輪郭抽出 : 2ms
- 最大輪郭の抽出 : 0.2msくらい
- その他の処理 : 2ms

2024-01-26 06:08 UTC, YusukeKato commented
画像サイズを小さくしたときの画像処理とpublish処理にかかった時間を計測しました。

デフォルトの画像サイズの場合（640x480、2値化はinRange()を使用、rqt_image_view起動時）

- 画像処理 : 10ms
- publish : 60ms

画像サイズを320x240に変更した場合（2値化はinRange()を使用、rqt_image_view起動時）

- 画像処理 : 5ms
- publish : 9ms

画像サイズ320x240でadaptiveThreshold() を使用（rqt_image_view起動時）

- 画像処理 : 10ms（そのうちadaptiveThreshold() が6ms）
- publish : 9ms

2024-01-26 07:13 UTC, YusukeKato commented
ヒストグラム平坦化について調査しました。

参考 : https://docs.opencv.org/4.x/d6/dc7/group__imgproc__hist.html#ga7e54091f0c937d49bf84152a16f76d6e

使用方法

```cpp
cv::equalizeHist(input_gray_image, output_hist_equalized_image);
```

ヒストグラム平坦化の処理にかかる時間は1ms以内でした。

ヒストグラム平坦化前のグレイスケール画像↓

![gray](https://github.com/rt-net/raspimouse_ros2_examples/assets/12107761/24969350-ceff-4710-8494-852bfde9f41b)

ヒストグラム平坦化を行ったグレイスケール画像↓

![hist_equalized_gray](https://github.com/rt-net/raspimouse_ros2_examples/assets/12107761/2a0a45f5-adbd-4d8d-9f26-124fa75a4458)

2024-01-26 07:27 UTC, YusukeKato commented
adaptiveThreshold関数によるグレイスケール画像の2値化

```cpp
cv::adaptiveThreshold(gray, extracted_bin, 255, CV_ADAPTIVE_THRESH_GAUSSIAN_C, CV_THRESH_BINARY_INV, 51, 0);
```

![adaptiveThreshold_image](https://github.com/rt-net/raspimouse_ros2_examples/assets/12107761/1a60c273-cc7b-4157-a240-a7a897644aac)

2024-02-02 09:46 UTC, YusukeKato commented
usb_camをlaunchファイルから起動する際に、ホワイトバランスと露光の自動調整機能をオフにしようとしましたが、うまくいきませんでした。そのため、以下のコマンドを実行して対処しています。

```sh
v4l2-ctl -c auto_exposure=1
v4l2-ctl -c white_balance_automatic=0
```

2024-02-05 01:28 UTC, ShotaAk commented
V4L2のパラメータ名が違うというのはissueにありました。
他の投稿を見ると、どうやらデバイスによって名称が変わるようです。
https://github.com/ros-drivers/usb_cam/issues/260

2024-02-05 01:49 UTC, ShotaAk requested changes
シミュレータで動作確認しました。

ROS パラメータ変更が適用されてOKです。
コメントの確認お願いします。

2024-02-05 01:49 UTC, ShotaAk commented on README.md
> +物体検出精度が悪い時にはカメラの露光や関数内のパラメータを調整して下さい。
ROSパラメータが用意されたので、パラメータを変更して調整できることを説明してください。

raspimouse2 パッケージのREADMEのように、パラメータ一覧を記載するとわかりやすいです。

2024-02-05 01:49 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +    cmd_vel.angular.z = ANGULAR_VEL * object_normalized_point_.x * 2.0;
ここの2.0 がどういう意味なのかわかるように定数にしてください。

2024-02-05 02:55 UTC, ShotaAk commented
ついでに、ライン検出の関数名を`detecting_line`から、`detect_line`に変更してもらえますか？

~ing という名称は、プロセスや状態に付けたいので。

2024-02-05 07:54 UTC, YusukeKato commented on src/camera_line_follower_component.cpp
> +    cmd_vel.angular.z = ANGULAR_VEL * object_normalized_point_.x * 2.0;
この2.0はデバッグ時に使用していた係数なので削除しました。

2.0を削除したことで回転方向の速度が変わりますが、ANGULAR_VELを調整することで対応できると思います。

```sh
constexpr double ANGULAR_VEL = -0.8;  // unit: rad/s
```

2024-02-05 07:57 UTC, YusukeKato commented
コメントありがとうございます。

`auto_exposure`と`white_balance_automatic`のパラメータに関して、いくつか名称を変更して試してみましたが、露光とホワイトバランスの自動調整はオフにできませんでした。

https://github.com/rt-net/raspimouse_ros2_examples/pull/49#issuecomment-1926057951

2024-02-05 09:06 UTC, ShotaAk commented
カメラパラメータについて言葉足らずでした。

他の投稿を見ると、どうやらデバイスによって名称が変わるようです。
なので、usb_cam側に柔軟なパラメータが必要ですね。

サンプルのlaunchファイル側でv4l2-ctrlコマンドを実行することもできますが、
カメラ機種依存になるのでいい方法出ないですね。

2024-02-05 09:08 UTC, ShotaAk commented on README.en.md
> +```
Parametersの説明が追加されたので、Configureの説明は削除してOKです

2024-02-05 09:08 UTC, ShotaAk commented on README.en.md
> +```
日本語READMEも同様にお願いします。

2024-02-05 09:12 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  declare_parameter(BRIGHTNESS_MAX_VAL_PARAM, 100);
![image](https://github.com/rt-net/raspimouse_ros2_examples/assets/18494952/fcb4a5f8-2f77-4d6e-a7d2-5446ead92aa2)


私の環境だとライントレースに失敗します。

デフォルト値を90にしてもらえませんか？

2024-02-05 09:16 UTC, ShotaAk commented on src/camera_line_follower_component.cpp
> +  declare_parameter(BRIGHTNESS_MAX_VAL_PARAM, 100);
READMEに記載している数値も変更お願いします。

2024-02-05 09:30 UTC, YusukeKato commented on src/camera_line_follower_component.cpp
> +  declare_parameter(BRIGHTNESS_MAX_VAL_PARAM, 100);
私の環境でもライントレースに失敗していました。

しきい値のデフォルト値を90に変更しました。

2024-02-05 09:51 UTC, ShotaAk approved these changes
LGTMです！

2024-02-05 09:52 UTC, merged