SubscriberとService Clientに別々のcallback_groupを設定
rt-net/raspimouse_ros2_examples pull request #58
Opened 2024-08-08 05:38 UTC by YusukeKato

# What does this implement/fix?

#56 で指摘されている問題を解決するためにSubscriberとService Clientに別々のcallback_groupを設定します。

# Does this close any currently open issues?

#56 に対応します。

# How has this been tested?

実機のRaspberry Pi Mouseでジョイスティックコントローラから全てのノードを停止できることを確認しました。

# Any other comments?

## ノードの終了方法
joystick_controlノードの中でjoystick_controlノードの削除を行った後はターミナルがそのまま停止してしまうので、下記の行にて手動で例外を発生させて終了させています。この方法で問題ないか確認いただきたいです。
https://github.com/rt-net/raspimouse_ros2_examples/blob/set_callback_group/raspimouse_ros2_examples/joystick_control.py#L207

参考：https://answers.ros.org/question/406469/ros-2-how-to-quit-a-node-from-within-a-callback/

## callback_groupの種類
下記のどちらのcallback_groupでも正常に動きますが、どちらがよいかなど確認していただきたいです。

- MutuallyExclusiveCallbackGroup()
- ReentrantCallbackGroup()

参考：https://docs.ros.org/en/humble/How-To-Guides/Using-callback-groups.html

## 終了時の処理のログ
ジョイスティックコントローラからシャットダウン処理を行った際、すべてのノードが終了することは確認できましたが、下記のようにエラーのログが出ています。これで問題ないか確認していただきたいです。

```
[raspimouse-3] [INFO] [1723095315.346715360] [raspimouse]: Deactivating node
[raspimouse-3] [INFO] [1723095315.346896007] [raspimouse]: Turned motors off
[raspimouse-3] [INFO] [1723095315.347719091] [raspimouse]: Turned motors off
[joystick_control.py-2] [INFO] [1723095315.768695813] [joystick_control]: _joy_shutdown() has been executed
[INFO] [joystick_control.py-2]: process has finished cleanly [pid 7848]
[ERROR] [launch]: Caught exception in launch (see debug for traceback): expected a LaunchDescriptionEntity from event_handler, got '<launch.events.shutdown.Shutdown object at 0xffff8a1d4e20>'
[INFO] [raspimouse-3]: sending signal 'SIGINT' to process[raspimouse-3]
[INFO] [joy_linux_node-1]: sending signal 'SIGINT' to process[joy_linux_node-1]
[raspimouse-3] [INFO] [1723095316.570058723] [rclcpp]: signal_handler(signum=2)
[raspimouse-3] [INFO] [1723095316.571776336] [raspimouse]: Turned motors off
[joy_linux_node-1] [INFO] [1723095316.574347293] [rclcpp]: signal_handler(signum=2)
[raspimouse-3] [ERROR] [1723095316.581752111] [raspimouse]: Unable to start transition 6 from current state shuttingdown: Could not publish transition: publisher's context is invalid, at ./src/rcl/publisher.c:389, at ./src/rcl_lifecycle.c:368
[raspimouse-3] [WARN] [1723095316.581824166] [rclcpp_lifecycle]: Shutdown error in destruction of LifecycleNode: final state(shuttingdown)
[joy_linux_node-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[joy_linux_node-1]   what():  failed to create guard condition: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at ./src/rcl/guard_condition.c:67
[INFO] [raspimouse-3]: process has finished cleanly [pid 7850]
[ERROR] [joy_linux_node-1]: process has died [pid 7846, exit code -6, cmd '/opt/ros/humble/lib/joy_linux/joy_linux_node --ros-args --params-file /tmp/launch_params_972nvo76'].
```

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-08-08 08:29 UTC, ShotaAk commented
> [raspimouse-3] [ERROR] [1723095316.581752111] [raspimouse]: Unable to start transition 6 from current state shuttingdown: Could not publish transition: publisher's context is invalid, at ./src/rcl/publisher.c:389, at ./src/rcl_lifecycle.c:368

このエラーログについて、ラズパイマウスを別ターミナルで起動してても発生しますか？

また、同じターミナルで起動する場合、Ctrl+Cで終了しても発生しますか？

2024-08-08 08:42 UTC, ShotaAk requested changes
Gazebo環境にて動作確認しました。

コメントの確認お願いします。

2024-08-08 08:42 UTC, ShotaAk commented on raspimouse_ros2_examples/joystick_control.py
> +        self._client_cb_group = MutuallyExclusiveCallbackGroup()
ここの実装OKです。

sub_cbについてはデータ競合がないため、Reentrantにして高速化が狙えます。
（が、そもそも高速で動かす必要がないので、このままでOKです）

2024-08-08 08:42 UTC, ShotaAk commented on raspimouse_ros2_examples/joystick_control.py
> +        self._client_get_state = self.create_client(
ここ以降のクライアントの宣言ですが、サブスクライバの宣言よりも上に持ってきてください。

サービスクライアントが生成される前に、トピックのコールバックが発生して、
存在しないクライアントを使う可能性があるためです。

2024-08-08 08:42 UTC, ShotaAk commented on raspimouse_ros2_examples/joystick_control.py
> +            raise SystemExit
joy_linux_nodeの挙動により、StartとSelectを押してシャットダウンした後、再度ノードをlaunchすると、
前回のStartとSelect押下状態が再配信されます。
これにより、サンプルが起動してすぐに終了します。

おそらく、ROSネットワークが生きている状態（mouseノードを別ターミナルで起動した状態）で発生していると思います。
対策案がないか調べてください。（joy_linux_nodeにパラメータがあるかも？）

2024-08-19 02:48 UTC, YusukeKato commented
下記の件について確認しました。
https://github.com/rt-net/raspimouse_ros2_examples/pull/58#issuecomment-2275251166

> > [raspimouse-3] [ERROR] [1723095316.581752111] [raspimouse]: Unable to start transition 6 from current state shuttingdown: Could not publish transition: publisher's context is invalid, at ./src/rcl/publisher.c:389, at ./src/rcl_lifecycle.c:368
> 
> このエラーログについて、ラズパイマウスを別ターミナルで起動してても発生しますか？
> 
> また、同じターミナルで起動する場合、Ctrl+Cで終了しても発生しますか？

結果：どちらの場合でも同様のエラーログが出ているようです。

## ラズパイマウスを別ターミナルで起動した場合
ジョイスティックコントローラのボタンで停止させた
### terminal 1
```sh
ubuntu@ubuntu:~/ros2_ws_20240807$ ros2 run raspimouse raspimouse
〜省略〜
[INFO] [1724035078.077804230] [raspimouse]: Turned motors off
[ERROR] [1724035078.087124237] [raspimouse]: Unable to start transition 6 from current state shuttingdown: Could not publish transition: publisher's context is invalid, at ./src/rcl/publisher.c:389, at ./src/rcl_lifecycle.c:368
[WARN] [1724035078.087224866] [rclcpp_lifecycle]: Shutdown error in destruction of LifecycleNode: final state(shuttingdown)
```

### terminal 2
```sh
ubuntu@ubuntu:~/ros2_ws_20240807$ ros2 launch raspimouse_ros2_examples teleop_joy.launch.py mouse:=false
〜省略〜
[joystick_control.py-2] [INFO] [1724035067.295789081] [joystick_control]: _joy_shutdown() has been executed
[INFO] [joystick_control.py-2]: process has finished cleanly [pid 2445]
[ERROR] [launch]: Caught exception in launch (see debug for traceback): expected a LaunchDescriptionEntity from event_handler, got '<launch.events.shutdown.Shutdown object at 0xffffb5604e50>'
[INFO] [joy_linux_node-1]: sending signal 'SIGINT' to process[joy_linux_node-1]
[joy_linux_node-1] [INFO] [1724035067.450120225] [rclcpp]: signal_handler(signum=2)
[joy_linux_node-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[joy_linux_node-1]   what():  failed to create guard condition: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at ./src/rcl/guard_condition.c:67
[ERROR] [joy_linux_node-1]: process has died [pid 2443, exit code -6, cmd '/opt/ros/humble/lib/joy_linux/joy_linux_node --ros-args --params-file /tmp/launch_params_6_zox577'].
```

## Ctrl+Cで停止させた場合
```sh
ubuntu@ubuntu:~/ros2_ws_20240807$ ros2 launch raspimouse_ros2_examples teleop_joy.launch.py joydev:="/dev/input/js0" joyconfig:=f710 mouse:=true
〜省略〜
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[joy_linux_node-1] [INFO] [1724035401.837357277] [rclcpp]: signal_handler(signum=2)
[INFO] [raspimouse-3]: process has finished cleanly [pid 2574]
[raspimouse-3] [INFO] [1724035401.837344925] [rclcpp]: signal_handler(signum=2)
[raspimouse-3] [INFO] [1724035401.841008502] [raspimouse]: Turned motors off
[raspimouse-3] [ERROR] [1724035401.972842103] [raspimouse]: Unable to start transition 7 from current state shuttingdown: Could not publish transition: publisher's context is invalid, at ./src/rcl/publisher.c:389, at ./src/rcl_lifecycle.c:368
[raspimouse-3] [WARN] [1724035401.972927140] [rclcpp_lifecycle]: Shutdown error in destruction of LifecycleNode: final state(shuttingdown)
[joystick_control.py-2] Traceback (most recent call last):
[joystick_control.py-2]   File "/home/ubuntu/ros2_ws_20240807/install/raspimouse_ros2_examples/lib/raspimouse_ros2_examples/joystick_control.py", line 422, in <module>
[joystick_control.py-2]     main()
[joystick_control.py-2]   File "/home/ubuntu/ros2_ws_20240807/install/raspimouse_ros2_examples/lib/raspimouse_ros2_examples/joystick_control.py", line 412, in main
[joystick_control.py-2]     rclpy.spin(joy_wrapper)
[joystick_control.py-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
[joystick_control.py-2]     executor.spin_once()
[joystick_control.py-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
[joystick_control.py-2]     self._spin_once_impl(timeout_sec)
[joystick_control.py-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 728, in _spin_once_impl
[joystick_control.py-2]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[joystick_control.py-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 711, in wait_for_ready_callbacks
[joystick_control.py-2]     return next(self._cb_iter)
[joystick_control.py-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 608, in _wait_for_ready_callbacks
[joystick_control.py-2]     wait_set.wait(timeout_nsec)
[joystick_control.py-2] KeyboardInterrupt
[joy_linux_node-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[joy_linux_node-1]   what():  failed to create guard condition: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at ./src/rcl/guard_condition.c:67
[ERROR] [joystick_control.py-2]: process has died [pid 2572, exit code -2, cmd '/home/ubuntu/ros2_ws_20240807/install/raspimouse_ros2_examples/lib/raspimouse_ros2_examples/joystick_control.py --ros-args --params-file /home/ubuntu/ros2_ws_20240807/install/raspimouse_ros2_examples/share/raspimouse_ros2_examples/config/joy_f710.yml'].
[ERROR] [launch]: Caught exception in launch (see debug for traceback): expected a LaunchDescriptionEntity from event_handler, got '<launch.events.shutdown.Shutdown object at 0xffffaf5d4e80>'
[ERROR] [joy_linux_node-1]: process has died [pid 2570, exit code -6, cmd '/opt/ros/humble/lib/joy_linux/joy_linux_node --ros-args --params-file /tmp/launch_params_kjf5k36n'].
```

2024-08-19 03:10 UTC, YusukeKato commented on raspimouse_ros2_examples/joystick_control.py
> +            raise SystemExit
私のほうでもraspimouse_sim環境でこちらの問題を再現できました。
実機ではmouseノードを別ターミナルで起動していてもこちらの問題は再現されませんでした。

2024-08-19 09:20 UTC, YusukeKato commented on raspimouse_ros2_examples/joystick_control.py
> +            raise SystemExit
１つ目のターミナルでシミュレータを起動、２つ目のターミナルでジョイスティックコントローラの操作ノードを起動させた状態で、一度ジョイスティックコントローラからの操作でノードを停止させると、再度ジョイスティックコントローラのノードを立ち上げて何も操作していなくても、下記のように/joyトピックが配信されていることを確認しました。
（正常にjoy_linux_nodeが終了しなかったことが原因で、ROS側の何かしらの理由で/joyトピックが永遠に配信され続けている？）
```
ubuntu@ubuntu:~$ ros2 topic echo /joy
〜省略〜
---
header:
  stamp:
    sec: 1724058602
    nanosec: 652195417
  frame_id: joy
axes:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
buttons:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 1
- 1
- 0
- 0
---
```

2024-08-20 01:47 UTC, ShotaAk commented on raspimouse_ros2_examples/joystick_control.py
> +            raise SystemExit
調査ありがとうございます。

joy_nodeが終了するまでに時間がかかっているのが原因のようですね。
サンプル側での解決手段がすぐに出てこないので、一旦マージしましょう。

2024-08-20 01:56 UTC, ShotaAk commented
エラーログについても調査ありがとうございます。
シャットダウン状態からの状態遷移に関するエラーメッセージであり、直接問題にはなってないので対応なしにしましょう。

2024-08-20 01:57 UTC, ShotaAk approved these changes
LGTM

2024-08-20 01:57 UTC, merged